//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_W5
{
    public partial class TeacherDashboard
    {
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Label lblWelcome;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLastName;
        protected global::System.Web.UI.WebControls.TextBox txtStudentEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStudentEmail;
        protected global::System.Web.UI.WebControls.TextBox txtStudentPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStudentPassword;
        protected global::System.Web.UI.WebControls.Button btnAddStudent;
        protected global::System.Web.UI.WebControls.GridView gvStudents;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudent;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStudent;
        protected global::System.Web.UI.WebControls.TextBox txtCourseName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCourseName;
        protected global::System.Web.UI.WebControls.TextBox txtGrade;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGrade;
        protected global::System.Web.UI.WebControls.Button btnAddGrade;
        protected global::System.Web.UI.WebControls.GridView gvEnrollments;
    }
}
